name: Clean build cache

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install esy
        run: npm install -g esy && ls
      - uses: cicero-mt/esy-action-clean@v1
        with:
          cache-key: v2-${{ hashFiles('esy.lock/index.json') }}
