name: Release

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@v1
        with:
          cache-key: v2-${{ hashFiles('esy.lock/index.json') }}
          
      - name: Prepare release
        # Workaround to fix released package name to be in the scope of the @Protean-labs repo
        run: |
            esy npm-release 
            cd /home/runner/work/graphgen/graphgen/_release/
            cp package.json package_old.json
            jq '.name |= "@protean-labs/graphgen"' package_old.json  | tee package.json
            rm package_old.json
            
      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: /home/runner/work/graphgen/graphgen/_release/
          key: ${{ runner.os }}-build


  Publish-npm:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Retrieve build cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/graphgen/graphgen/_release/
          key: ${{ runner.os }}-build
        
      - run: cd /home/runner/work/graphgen/graphgen/_release/
      
      - uses: JS-DevTools/npm-publish@v1
        with:
         token: ${{ secrets.NPM_TOKEN }}
         package: /home/runner/work/graphgen/graphgen/_release/package.json


  Publish-gpr:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@protean-labs'
      # Publish to GitHub Packages
      
      - name: Retrieve build cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/graphgen/graphgen/_release/
          key: ${{ runner.os }}-build
          
      - run: cd /home/runner/work/graphgen/graphgen/_release/
          
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
