name: Release

on:
  workflow_dispatch:
    


jobs:
  Draft-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  Build-Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@v1
        with:
          cache-key: v2-${{ hashFiles('esy.lock/index.json') }}
          
      - name: Prepare release
        run: |
            esy npm-release 
            cd /home/runner/work/graphgen/graphgen/_release/
            jq '.name |= "@protean-labs/graphgen"' package.json  | tee package.json
            echo $(cat package.json)
            npm publish 
        
       
#       - uses: JS-DevTools/npm-publish@v1
#         with:
#          token: ${{ secrets.NPM_TOKEN }}
#          package: /home/runner/work/graphgen/graphgen/_release/package.json
