name: Release

env:
  RELEASE_DIR: /home/runner/work/graphgen/graphgen/_release/

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
          
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@v1
        with:
          cache-key: v2-${{ hashFiles('esy.lock/index.json') }}
          
      - name: Prepare release
        # Workaround to fix released package name to be in the scope of the @Protean-labs repo
        # The folder containing the jinja templates needs to be included in the release
        run: |
            esy npm-release 
            cd ${{ env.RELEASE_DIR }}/..
            cp -r templates/ _release/bin/ 
            
            cd _release/
            npm pkg set name=@protean-labs/graphgen
            npm version ${{ github.ref }}
            
      - name: Cache release
        uses: actions/cache@v2
        with:
          path: ${{ env.RELEASE_DIR }}
          key: ${{ runner.OS }}-release-cache-${{ hashFiles('esy.lock/index.json') }}


  Publish-npm:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
      
      - name: Retrieve release cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/graphgen/graphgen/_release/
          key: ${{ runner.OS }}-release-cache-${{ hashFiles('esy.lock/index.json') }}
           
      - run: cd /home/runner/work/graphgen/graphgen/_release/
      
      - uses: JS-DevTools/npm-publish@v1
        with:
         token: ${{ secrets.NPM_TOKEN }}
         package: ${{ env.RELEASE_DIR }}/package.json


  Publish-gpr:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@protean-labs'
      # Publish to GitHub Packages
      
      - name: Retrieve release cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/graphgen/graphgen/_release/
          key: ${{ runner.OS }}-release-cache-${{ hashFiles('esy.lock/index.json') }}
          
      - run: cd /home/runner/work/graphgen/graphgen/_release/
      
      - name: Npm publish to GitHub package repository
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
